### ISSUE TITLE
Which reference implementation is better?

### ISSUE THREAD

**Issue by danghvu** [graph500/graph500#13]
The new 3.0.0 release is using AM model (implemented using MPI3) (namely _aml_) instead of a direct MPI implementation as in older reference (2.x). Is there a study about this new reference implementation in comparison with the old one ? Do you have insight on how much we gain/loss using this new approach ?

**Comment by akorzh** [comment]
probably too late to be replied - sorry for that
so first of all, reference wasnt measnt to be of any high performance, so comparing performance wasnt a concern yet,or subject to study.

secondly, i believe aml based version scales somewhat better for sure

third, only aml-based reference includes SSSP kernel, so its the one recommended to be used
fourth, hopefully we will release much faster reference (not the top speed, but close to it) in the coming year(hopefully by next ISC list). The code exists of today just should be cleaned up debugged etc. It would implement most of publicly known tricks like degree-aware load balancing, direction optimization etc
