### ISSUE TITLE
Missing waitall in aml_finalize 

### ISSUE THREAD

**Issue by nSircombe** [graph500/graph500#14]
Recently stumbled over an issue running Graph500 on an AArch64 platform, building with the Arm HPC Compiler and OpenMPI 3.1.1, with OpenUCX.
This was initially suspected to be a memory leak in OpenUCX and raised as an issue on the OpenUXC GitHub (https://github.com/openucx/ucx/issues/2777). 
However, the issue appears to be with aml/aml.c in Graph500, and can be remedied - see https://github.com/openucx/ucx/issues/2777#issuecomment-412520232.

**Comment by akorzh** [comment]
oh, you guy run our stuff on ARM - thats pretty cool
hope you will submit something
though todays reference is not really designed for performance - its more like reference
but if you have large system shoot me an email - we can chat about it

and thanks for the bug - i now remember i had it too sometimes:) will fix in newer versions!

**Comment by nSircombe** [comment]
Yep - no trouble building with GCC and the Arm HPC Compiler on AArch64 (nothing Arm-specific anyway, and that bug above only made it's presence known when using an OpebUCX layer in OpenMPI).
At the moment this has just been to check it builds & runs OK, so only single-node scale jobs so far.

**Comment by nSircombe** [comment]
I forgot to mention - that was with the newreference branch, not the v3.0.0 tag

**Comment by akorzh** [comment]
fixed today
