### ISSUE TITLE
Fix to Issue#8 appears to be missing from master and 3.0.0 branches

### ISSUE THREAD

**Issue by nSircombe** [graph500/graph500#15]
I've been trying to build Graph500 v3.0.0 with clang (starting both from the tarball at https://github.com/graph500/graph500/archive/graph500-3.0.0.tar.gz and the graph500-3.0.0 tag int he repo).

I've run into some issues identified previously in https://github.com/graph500/graph500/issues/8
Specifically a series of undefined references. The code compiles with GCC but issues warnings of the form "warning: ‘sendsize_intra’ is static but used in inline function ‘aml_send_intra’ which is not static".

The following ifdef in aml.c, introduced to resolve issue 8, is absent from the v3.0.0 tag and master branch.

```
#ifdef __clang__
 #define inline static inline
 #endif
```

Putting this back means the code compiles fine with clang. Could this be added to the release version and tagged in the repo too?

**Comment by akorzh** [comment]
https://github.com/graph500/graph500/archive/3.0.1.tar.gz
released, hope that helps
