### ISSUE TITLE
Generating graphs in edgelist text format

### ISSUE THREAD

**Issue by vaastav** [graph500/graph500#19]
Hi,
I followed the instructions to use TMPFILE environment variable to obtain the graph that was generated during BFS/SSSP. But the generated graph is in binary format. I was wondering if there is a way to obtain the graph in text format or to convert the binary format into the txt format.

**Comment by akorzh** [comment]
you can look at the source - its pretty simple. Actually it writes just bunch of tuples v0 v1 where v0 and v1 are vertex numbers. it writes 5 bytes by default for each vertex but you can make it 8 easily and recode file. or just write text - hope that helps
