### ISSUE TITLE
problem making files

### ISSUE THREAD

**Issue by azlefty** [graph500/graph500#8]
Can you please help me.  I am trying to install and run the graph500 suite, on linux inside an Oracle VM VirtualBox on a windows 10 pc.  I am getting a compile error, as described below:

First I cloned the package from this git hub repository into my local workspace directory.
`$ git clone https://github.com/graph500/graph500.git`

Then I installed libmpich-dev in the linux shell:
`$ sudo apt-get install libmpich-dev`
which installed the package.  I confirmed it was installed:
`$ mpicc`
`Error: Command line argument is needed!`

Then I went to the src folder and tried to make the file.
`~/workspace$ cd graph500/src/`
`~/workspace/graph500/src$ make`
First I see

> mpicc -Drestrict=__restrict__ -O3 -DGRAPH_GENERATOR_MPI -DREUSE_CSR_FOR_VALIDATION -I../aml -DSSSP -lpthread -o graph500_reference_bfs_sssp bfs_reference.c sssp_reference.c csr_reference.c main.c utils.c validate.c ../aml/aml.c ../generator/graph_generator.c ../generator/make_graph.c ../generator/splittable_mrg.c ../generator/utils.c -lm
bfs_reference.c:113:19: warning: argument type 'long *' doesn't match specified 'MPI' type tag that requires 'long long *'
      [-Wtype-safety]
                aml_long_allsum(&sum);
                ~~~~~~~~~~~~~~~~^~~~~

etc.
Then there are several more type warnings.
Then the following errors related to the inline flush_buffer function:

> /tmp/aml-af4aed.o: In function `aml_barrier':
~/workspace/graph500/src/../aml/aml.c:383: undefined reference to `flush_buffer'
~/workspace/graph500/src/../aml/aml.c:398: undefined reference to `flush_buffer_intra'
~/workspace/graph500/src/../aml/aml.c:402: undefined reference to `aml_poll_intra'
~/workspace/graph500/src/../aml/aml.c:408: undefined reference to `aml_poll_intra'
/tmp/aml-af4aed.o: In function `aml_send_intra':
~/workspace/graph500/src/../aml/aml.c:214: undefined reference to `flush_buffer_intra'
/tmp/aml-af4aed.o: In function `aml_send':
~/workspace/graph500/src/../aml/aml.c:240: undefined reference to `flush_buffer'
/tmp/aml-af4aed.o: In function `aml_poll':
~/workspace/graph500/src/../aml/aml.c:156: undefined reference to `aml_poll_intra'
/tmp/aml-af4aed.o: In function `aml_send_intra':
~/workspace/graph500/src/../aml/aml.c:214: undefined reference to `flush_buffer_intra'
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [graph500_reference_bfs_sssp] Error 1
~/workspace/graph500/src$ 

Have you seen this and/or do you know what I am missing?  I see the flush_buffer inline function right inside the very same aml.c file.

Thanks 
Doug Bergman

**Comment by azlefty** [comment]
It worked when i removed the "inline" directives from the functions in aml.c.  See replaced file in attached zip.
[aml_c_noinlines.zip](https://github.com/graph500/graph500/files/1142880/aml_c_noinlines.zip)

**Comment by akorzh** [comment]
Wow that was fast :) thanks for reporting and investigating. Code wasn't testes that extensively, so I apologize. I normally used icc to build it.
Can you tell which compiler version were you using - I want to look into it. As this is reference version we care about portability so I am considering removing those inlines, but want to look into the issue first.

**Comment by azlefty** [comment]
I'm pretty new to C / C++ programming but here's the dump from typing "mpicc -v".  Does this answer the question?

~/workspace/graph500/src$ mpicc -v
mpicc for MPICH version 3.0.4
clang version 4.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
clang-4.0: warning: argument unused during compilation: '-D _FORTIFY_SOURCE=2'
clang-4.0: warning: argument unused during compilation: '-g'
clang-4.0: warning: argument unused during compilation: '-O2'
clang-4.0: warning: argument unused during compilation: '-fstack-protector'
clang-4.0: warning: argument unused during compilation: '--param ssp-buffer-size=4'
clang-4.0: warning: argument unused during compilation: '-Wformat'
clang-4.0: warning: argument unused during compilation: '-Werror=format-security'
clang-4.0: warning: argument unused during compilation: '-I /usr/include/mpich'
~/workspace/graph500/src$

**Comment by azlefty** [comment]
I don't know what is causing the strikethrough.

**Comment by akorzh** [comment]
i see that's clang and it's somewhat different from gcc/icc.
BTW I suppose you have used some standard VM image, right?

**Comment by akorzh** [comment]
i pushed new fix that fixes this, can you please check?
also make stuff build and run well on my MAC OS with homebrew-ed open-mpi
